### ISSUE TITLE
Desktop API alternative for Linux

### ISSUE THREAD

**Issue by nshusa** [nshusa/rsam-gui#11]
```java
Desktop.getDesktop().open(dir)
```

does not work on Linux, need an alternative for this.

**Comment by nshusa** [comment]
Temporarily disabled opening directory for linux 215e8b20adbd6c06221c51c63f30e61553ae7f43 will eventually want to support this for Linux users.

**Comment by IanWONeill** [comment]
https://stackoverflow.com/questions/8258153/how-to-get-desktop-class-supported-under-linux

**Comment by nshusa** [comment]
Going to close this for now since the main bug is fixed which was making the program unresponsive for Linux users who clicked option "Yes" to open the directory.
