### ISSUE TITLE
.JAG Icons

### ISSUE THREAD

**Issue by IanWONeill** [nshusa/rsam-gui#14]
I made an icon for the .jag files (:

![jag-icon-for-nshusa](https://user-images.githubusercontent.com/20154372/30521941-3f1b6bf4-9bc0-11e7-987b-73d291af0fe1.png)

**Comment by nshusa** [comment]
@IanWONeill Nice job :) I'll add it

**Comment by nshusa** [comment]
Added in commit c9ab6d6f20a65f785dfa5e36b7696be137aca357

**Comment by nshusa** [comment]
@IanWONeill Can you redo this so it's 32x32? The current icon looks odd since its 25x30 and all my other icons are 32x32

**Comment by IanWONeill** [comment]
![untitled-1](https://user-images.githubusercontent.com/20154372/30705814-7098775e-9eee-11e7-82cc-7d79fb7e5f7c.png)

Sorted.

**Comment by nshusa** [comment]
Much better, yeah the icon just has to be 32x32. Putting it in a 32x32 canvas like that worked.

![image](https://i.imgur.com/w5U94P5.png)

**Comment by nshusa** [comment]
Closing this now since it looks right now
